_D='ensemble'
_C='maListe'
_B='prenom'
_A='loto'
maListe=[]
print(_C,maListe)
print(_C,type(maListe))
maListe.append(11)
maListe.append('douze')
maListe.append(13.33)
print(_C,maListe)
maListe2=list()
loto=[22,33,44,44,55,77,88]
print(_A,loto)
loto.append(99)
loto+=[99]
loto.extend([99])
print(_A,loto)
loto.pop()
dernier=loto.pop()
print('dernier',dernier)
print(_A,loto)
loto=[11]+loto
loto.insert(0,11)
print(_A,loto)
premier=loto.pop(0)
print('premier',premier)
print(_A,loto)
indiceDe77=loto.index(77)
loto.insert(indiceDe77,66)
print(_A,loto)
loto.remove(44)
print(_A,loto)
ensemble=range(11,100,11)
print(_D,ensemble,type(ensemble))
ensemble=list(ensemble)
print(_D,ensemble,type(ensemble))
prenom='Olivier'
print(_B,prenom,type(prenom))
prenom=list(prenom)
print(_B,prenom,type(prenom))
prenom[3]='V'
prenom[-1]='R'
print(_B,prenom,type(prenom))
prenom=''.join(prenom)
print(_B,prenom,type(prenom))